
service: my-first-serverless-app

frameworkVersion: '3'

useDotenv: true # must be set to read from .env file

provider:
  name: aws
  runtime: nodejs16.x
  httpApi:
    cors: true
  environment:
    DUMMY_API_KEY: 'Dummy value'
    SECRET_API_KEY: ${env:SECRET_API_KEY} # points to variable in .env file

  stage: ${env:NODE_ENV, 'Production'} # If first is undefined, it defaults to second
  region: eu-central-1

functions:
  hello:
    handler: handler.hello
    memorySize: 512 # MB
    timeout: 30 # seconds
    environment:
      DUMMY_API_KEY: ${env:DUMMY_API_KEY, 'Default'}
    events:
      - httpApi:
          path: /
          method: get
      - httpApi:
          path: /create
          method: post

plugins:
  - serverless-offline
  - serverless-plugin-typescript
