
service: my-first-serverless-app

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x
  httpApi:
    cors: true
  environment:
    DUMMY_API_KEY: 'Dummy value'

  stage: dev
  region: eu-central-1

functions:
  hello:
    handler: handler.hello
    environment:
      DUMMY_API_KEY: 'New Dummy value'
    events:
      - httpApi:
          path: /
          method: get
      - httpApi:
          path: /create
          method: post

plugins:
  - serverless-offline
  - serverless-plugin-typescript
